name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Lint
      run: |
        go vet -all .
        go install github.com/mgechev/revive@latest
        revive -config .revive.toml ./...

    - name: Test
      run: go test -v ./...
